[dev]
  command = "yarn start"

[build]
  command = "yarn build"
  publish = "out"
  functions = "functions"

[build.environment]
# Change this path with the path to your repository
GO_IMPORT_PATH="github.com/oanaOM/blossom"
